### ISSUE TITLE
delegate call execution doesn't return data

### ISSUE THREAD

**Issue by marcelomorgado** [zerodevapp/kernel#103]
The `returnData` is always empty when excuting a delegate call (Refs: https://github.com/zerodevapp/kernel/blob/dev/src/utils/ExecLib.sol#L54). Is there a reason for that?

**Comment by leekt** [comment]
good catch, adding fix for this on v3.1

**Comment by leekt** [comment]
it will be merged on #111

**Comment by Khaliq88** [comment]
> it will be merged on #111

gh pr checkout 112

**Comment by Khaliq88** [comment]
[](url)
