### ISSUE TITLE
How to Verify a Contract Account Created by KernelFactory?

### ISSUE THREAD

**Issue by wangyufsn** [zerodevapp/kernel#42]
I have observed that every contract account created by KernelFactory utilizes [low-level EVM code](https://github.com/zerodevapp/kernel/blob/main/src/factory/AdminLessERC1967Factory.sol#L138-L251) to instantiate a proxy instance. I am looking to verify each abstract account contract in my explorer, such as Blockcout. However, I am encountering difficulties due to the absence of proxy source code, with only EVM code available, making verification impossible.

I am interested in verifying contract accounts similar to this one: https://mumbai.polygonscan.com/address/0xc354BaCeB91E185dfeb4a1cA377F85CDE15b4097#code

Could anyone provide guidance on how to proceed with the verification of such contract accounts?

**Comment by leekt** [comment]
I'm pretty sure it's impossible to verify since it's technically written in bytecode so there aren't much to verify
