### ISSUE TITLE
SyntaxError: The requested module 'permissionless' does not provide an export named 'walletClientToCustomSigner'

### ISSUE THREAD

**Issue by francelwebdev** [zerodevapp/kernel#76]
node_modules/@zerodev/sdk/utils.ts:1
import { walletClientToCustomSigner } from "permissionless"

SyntaxError: The requested module 'permissionless' does not provide an export named 'walletClientToCustomSigner'

**Comment by leekt** [comment]
seems to be duplicate of https://github.com/zerodevapp/sdk/issues/88, closing since it's relevant to sdk
