### ISSUE TITLE
`forge build` error

### ISSUE THREAD

**Issue by eunseong-theori** [zerodevapp/kernel#78]
When I run `forge build`, I get the error:

`file cannot be resolved due to mismatch of file name case: "~/kernel/lib/forge-std/src/Console.sol": No such file or directory (os error 2)`

Changing `import {console} from "forge-std/Console.sol";` to lowercase `import {console} from "forge-std/console.sol";` solves the above problem.

https://github.com/zerodevapp/kernel/blob/eaaac83acd3e7695c742758a54828874ec0dcdee/src/utils/KernelTestBase.sol#L21

**Comment by leekt** [comment]
weird that it works on my machine, i'll fix this in separate pr though thanks for the input :)

**Comment by leekt** [comment]
fixed in #79
